name: CI/CD pipeline with docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    
jobs:
  image:
    name: Docker Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17

    - name: Build artifact
      run: mvn clean install

    - name: Build Docker image
      run: docker build -t pguillo02/query .

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      run: docker push pguillo02/query
      
